### ISSUE TITLE
Top SEO issues

### ISSUE THREAD

**Issue by linaxieNZ** [openlawnz/openlawnz-website#16]
- Need a sitemap.xml which can facilitate the chances of ranking by making the site easier to crawl by search engines.

- Two pages with duplicate <Title> tags: 
    https://www.openlaw.nz/how-to-use 
    https://www.openlaw.nz/how-to-use.html

- Add meta descriptions to each page

- Title tags are too short. Title tags need to deliver an important idea to potential readers in a few words. But if the title tag is too short, it will be difficult for search engines to understand what the content is about and decreasing the likelihood of ranking.

**Comment by BenRauzi** [comment]
Some of these should be handled by Gatsby now:

~~Need a sitemap.xml which can facilitate the chances of ranking by making the site easier to crawl by search engines~~.

~~Two pages with duplicate <Title> tags:
https://www.openlaw.nz/how-to-use
https://www.openlaw.nz/how-to-use.html~~

Add meta descriptions to each page - these should be improved.

Title tags are too short. Title tags need to deliver an important idea to potential readers in a few words. But if the title tag is too short, it will be difficult for search engines to understand what the content is about and decreasing the likelihood of ranking.
