### ISSUE TITLE
If the case name in search result is too long, the header, banner and footer are smaller than the width of the page

### ISSUE THREAD

**Issue by linaxieNZ** [openlawnz/openlawnz-website#7]
https://www.openlaw.nz/search.html?q=consumer

![body overflow](https://user-images.githubusercontent.com/26584515/91636877-337be280-ea58-11ea-9785-8b930753df7e.PNG)

**Comment by strum3nt** [comment]
The long title pushes out the width of the results table

**Comment by royastro-upstream** [comment]
How about we truncate the Case name link? The user would still be able to see the full case name by hovering over the link? See image below 
![image](https://user-images.githubusercontent.com/22050539/92298101-9fe76c00-ef99-11ea-9d89-b95201f3f614.png)

**Comment by williamparry** [comment]
I don't like the premise of design dictating data visibility (esp. for a table on desktop with no column resizing). I'd prefer to have a `max-width` and let it wrap.

**Comment by royastro-upstream** [comment]
Right, that is a good idea 👍

**Comment by royastro-upstream** [comment]
PR, case name has now max-width to 500px. Would look like below

![image](https://user-images.githubusercontent.com/22050539/92301994-81df3300-efbc-11ea-8b58-3d66b3beec6b.png)
